name: widgetbook_workspace
# ...
flutter:
  uses-material-design: true

dependencies:
  widgetbook_annotation: ^3.2.0
  widgetbook: ^3.9.0
  hygie_mobile:
    path: ../

dev_dependencies:
  build_runner:
  widgetbook_generator: ^3.9.0

environment:
  sdk: '>=3.0.0 <4.0.0'



