// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa1LfoH3RCT7cfnNEiMZaMfDbazrWNVrA',
    appId: '1:487775523474:web:66269fb50a26f12983cc4b',
    messagingSenderId: '487775523474',
    projectId: 'hygie-bc43a',
    authDomain: 'hygie-bc43a.firebaseapp.com',
    storageBucket: 'hygie-bc43a.appspot.com',
    measurementId: 'G-65QR6F5JB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL_dXr9WH9f1cVYeeIoz-SXT0JgklJ87A',
    appId: '1:487775523474:android:1f64ae7c098f402983cc4b',
    messagingSenderId: '487775523474',
    projectId: 'hygie-bc43a',
    storageBucket: 'hygie-bc43a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhhlzX66sFp75lAFPeNakiyAPWWWKIY8k',
    appId: '1:487775523474:ios:061c943e966651a383cc4b',
    messagingSenderId: '487775523474',
    projectId: 'hygie-bc43a',
    storageBucket: 'hygie-bc43a.appspot.com',
    iosClientId: '487775523474-ck6ou3ius2tpndm1ab8p2k1k95bp2ov2.apps.googleusercontent.com',
    iosBundleId: 'com.example.hygieMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhhlzX66sFp75lAFPeNakiyAPWWWKIY8k',
    appId: '1:487775523474:ios:061c943e966651a383cc4b',
    messagingSenderId: '487775523474',
    projectId: 'hygie-bc43a',
    storageBucket: 'hygie-bc43a.appspot.com',
    iosClientId: '487775523474-ck6ou3ius2tpndm1ab8p2k1k95bp2ov2.apps.googleusercontent.com',
    iosBundleId: 'com.example.hygieMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa1LfoH3RCT7cfnNEiMZaMfDbazrWNVrA',
    appId: '1:487775523474:web:5b7cd8e75a45097b83cc4b',
    messagingSenderId: '487775523474',
    projectId: 'hygie-bc43a',
    authDomain: 'hygie-bc43a.firebaseapp.com',
    storageBucket: 'hygie-bc43a.appspot.com',
    measurementId: 'G-LT1Z6GKYZB',
  );

}